version: "3.8"

name: Rently

services:
  rently-db:
    image: postgres:15
    container_name: rently-db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - rently_postgres_data:/var/lib/postgresql/data

  rently-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rently-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - rently-db

volumes:
  rently_postgres_data:
