spring.application.name=medical-staff-service
server.servlet.context-path=/api/v1
spring.datasource.url=jdbc:postgresql://localhost:15432/staff_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8082
patient-service.url=http://localhost:8088
auth-service.url=http://localhost:8082
spring.config.import=optional:configserver:http://localhost:8888
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}