spring.datasource.url=jdbc:postgresql://healthy_postgres:5432/alert_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.multiplier=1.5
spring.cloud.config.retry.max-interval=10000

server.servlet.context-path=/api/v1

medical-staff-service.url=http://medical-staff-service
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}