spring.application.name=iot-integration-service

server.port=8083

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword
spring.config.import=optional:configserver:http://localhost:8888
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}