spring.application.name=visit-service
server.servlet.context-path=/api/v1
spring.datasource.url=jdbc:postgresql://localhost:15432/visit_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8089
spring.config.import=optional:configserver:http://localhost:8888