version: "3.8"

name: Rently

services:
  rently-db:
    image: postgres:15
    container_name: rently-db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - rently_postgres_data:/var/lib/postgresql/data

  sonar-db:
    image: postgres:15
    container_name: sonar-db
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - sonar_postgres_data:/var/lib/postgresql/data

  rently-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rently-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - rently-db
      - sonar-db

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonarqube
      SONAR_JDBC_USERNAME: user
      SONAR_JDBC_PASSWORD: password
    depends_on:
      - sonar-db

volumes:
  rently_postgres_data:
  sonar_postgres_data:
