# Generated by Django 5.2.4 on 2025-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('local_path', models.FilePathField(blank=True, null=True, path='media/videos')),
            ],
        ),
    ]
