keycloak.server-url=http://keycloak-server:9090
keycloak.realm=healthmonitor-realm
keycloak.client-id=auth-service-backend
keycloak.client-secret=Q4T6eRN5lB520VuELv77mJW8BBZbwKVz
spring.rabbitmq.host=message_broker
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=20
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.multiplier=1.5
spring.cloud.config.retry.max-interval=10000
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}