spring.application.name=auth-service

server.port=8087

keycloak.server-url=http://localhost:9090
keycloak.realm=healthmonitor-realm
keycloak.client-id=auth-service-backend
keycloak.client-secret=Q4T6eRN5lB520VuELv77mJW8BBZbwKVz

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}