server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
          routes:
            - id: patient-service-route
              uri: lb://patient-service
              predicates:
                - Path=/api/v1/patients/**
            - id: medical-staff-service-route
              uri: lb://medical-staff-service
              predicates:
                - Path=/api/v1/staff/**
            - id: vital-signs-service-route
              uri: lb://vital-signs-service
              predicates:
                - Path=/api/v1/vital-signs/**
            - id: notification-service-route
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications/**, /api/v1/ws-notifications/**
            - id: auth-service-route
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: iot-integration-service-route
              uri: lb://iot-integration-service
              predicates:
                - Path=/api/v1/integration/**
            - id: visit-service-route
              uri: lb://visit-service
              predicates:
                - Path=/api/v1/visits/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/healthmonitor-realm

  reactor:
    context-propagation: auto

medical-staff-service:
  url: http://localhost:8082

patient-service:
  url: http://localhost:8088

visit-service:
  url: http://localhost:8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}