spring:
  #  config:
  #    import: configserver:http://localhost:8888
  application:
    name: RENTLYAUTH
  cloud:
    discovery:
      enabled: true
#  profiles:
#    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}
  security:
    oauth2:
      authorizationserver:
        issuer-uri: http://localhost:8080
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: email
server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework
#  ssl:
#    enabled: false
#    key-store:
#    key-password:
#    key-store-type: PKCS12
#    key-alias:
authserver:
  jwk:
    key:
      alias: auth
    keystore:
      path: ${KEYSTORE_PATH}
      password: ${KEYSTORE_PASSWORD}
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE  # To pokaże wartości parametrów w zapytaniach SQL
springdoc:
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
#eureka:
#  instance:
#    prefer-ip-address: false
#    hostname: localhost
#openapi:
#  v3:
#    servers:
#      - url: /rentlyauth
#        description: Adres przez API Gateway