spring:
  application:
    name: Rental-listing-service
  datasource:
#    url: jdbc:postgresql://localhost:5432/Listings nie wiem czemu se własny kontener stworzyłeś XDDD
#    username: postgres
#    password: haslo
    url: jdbc:postgresql://localhost:5432/app_db
    username: user
    password: password
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
# Konfiguracja swaggera
# - UI Swaggera: http://localhost:8080/swagger-ui.html
# - JSON OpenAPI: http://localhost:8080/api-doc
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operationsSorter: method to nie działa
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
server:
  port: 3002