spring:
 datasource:
   url: jdbc:postgresql://localhost:5432/app_db
   username: user
   password: password
# Dialekt JPA
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost